/**
 * Tests for scripts/seed-d1-from-json.ts pure transformations.
 * Traces to FR-49 AC-49.3.
 */
import { describe, it, expect } from 'vitest';
import {
  buildSeedSql,
  billKey,
  sqlString,
  sqlNumber,
  sqlBool,
} from '../../scripts/seed-d1-from-json';

const ISO = '2026-05-02T20:00:00.000Z';
const TRACE = 'tr_aaaaaaaaaaaaaaaa';

let counter = 0;
const newId = () => `01HQ${String(counter++).padStart(22, '0')}`;

describe('seed-d1 helpers', () => {
  it('billKey composes the FR-32 bill_id shape', () => {
    expect(billKey({ congress: 117, type: 'HR', number: '2471' })).toBe('117-HR-2471');
    expect(billKey({ congress: 119, type: 'S', number: '1234' })).toBe('119-S-1234');
  });

  it('sqlString quotes and escapes single quotes', () => {
    expect(sqlString('hello')).toBe("'hello'");
    expect(sqlString("don't")).toBe("'don''t'");
    expect(sqlString(null)).toBe('NULL');
    expect(sqlString(undefined)).toBe('NULL');
  });

  it('sqlNumber serializes finite numbers, else NULL', () => {
    expect(sqlNumber(0)).toBe('0');
    expect(sqlNumber(1.5)).toBe('1.5');
    expect(sqlNumber(null)).toBe('NULL');
    expect(sqlNumber(undefined)).toBe('NULL');
    expect(sqlNumber(NaN)).toBe('NULL');
    expect(sqlNumber(Infinity)).toBe('NULL');
  });

  it('sqlBool emits 1 / 0', () => {
    expect(sqlBool(true)).toBe('1');
    expect(sqlBool(false)).toBe('0');
    expect(sqlBool(undefined)).toBe('0');
  });
});

describe('buildSeedSql (FR-49 AC-49.3)', () => {
  it('emits header + seed researcher row + INSERT OR IGNORE for each bill', () => {
    counter = 0;
    const bills = [
      {
        congress: 117,
        type: 'HR',
        number: '2471',
        title: 'Consolidated Appropriations Act, 2022',
        direction: 'pro-ukraine',
      },
    ];
    const sql = buildSeedSql(bills, { isoNow: ISO, traceId: TRACE, newId });
    expect(sql).toContain('-- Generated by scripts/seed-d1-from-json.ts');
    expect(sql).toContain(`-- Run trace: ${TRACE}`);
    expect(sql).toContain("INSERT OR IGNORE INTO researchers");
    expect(sql).toContain("'seed'");
    expect(sql).toContain('INSERT OR IGNORE INTO bills');
    expect(sql).toContain("'117-HR-2471'");
    expect(sql).toContain("'Consolidated Appropriations Act, 2022'");
    expect(sql).toContain('INSERT OR IGNORE INTO audit_log');
    expect(sql).toContain(`'${TRACE}'`);
    expect(sql).toContain("'seed-bills-117-HR-2471'");
  });

  it('emits one INSERT per nested vote with deterministic audit IDs', () => {
    counter = 0;
    const bills = [
      {
        congress: 117,
        type: 'HR',
        number: '2471',
        title: 'Test',
        direction: 'pro-ukraine',
        votes: [
          {
            chamber: 'House' as const,
            congress: 117,
            session: 2,
            rollCall: 65,
            date: '2022-03-10T02:49:07Z',
            weight: 0.9,
            directionMultiplier: 1,
            kind: 'concur',
          },
          {
            chamber: 'Senate' as const,
            congress: 117,
            session: 2,
            rollCall: 78,
            date: '2022-03-11T04:02:38Z',
            weight: 0.9,
            directionMultiplier: 1,
            kind: 'concur',
          },
        ],
      },
    ];
    const sql = buildSeedSql(bills, { isoNow: ISO, traceId: TRACE, newId });
    expect(sql.match(/INSERT OR IGNORE INTO votes/g)?.length).toBe(2);
    expect(sql).toContain("'seed-votes-House-117-2-65'");
    expect(sql).toContain("'seed-votes-Senate-117-2-78'");
    // Vote audit row carries the bill+chamber+rollcall in row_title.
    expect(sql).toContain("'117-HR-2471 / House roll 65'");
    expect(sql).toContain("'117-HR-2471 / Senate roll 78'");
  });

  it('escapes single quotes in titles and labels', () => {
    counter = 0;
    const bills = [
      {
        congress: 118,
        type: 'HR',
        number: '999',
        title: "Don't Stop Believin'",
        label: "Murphy's Law",
        direction: 'pro-ukraine',
      },
    ];
    const sql = buildSeedSql(bills, { isoNow: ISO, traceId: TRACE, newId });
    expect(sql).toContain("'Don''t Stop Believin'''");
    expect(sql).toContain("'Murphy''s Law'");
  });

  it('serializes summary as JSON string', () => {
    counter = 0;
    const bills = [
      {
        congress: 118,
        type: 'HR',
        number: '1',
        title: 't',
        direction: 'pro-ukraine',
        summary: { text: 'foo', actionDate: '2024-01-01' },
      },
    ];
    const sql = buildSeedSql(bills, { isoNow: ISO, traceId: TRACE, newId });
    // summary_json appears as a JSON-encoded string literal.
    expect(sql).toMatch(/'\{"text":"foo","actionDate":"2024-01-01"\}'/);
  });

  it('is idempotent on re-emission with same inputs (deterministic audit IDs)', () => {
    counter = 0;
    const bills = [
      {
        congress: 117,
        type: 'HR',
        number: '2471',
        title: 'T',
        direction: 'pro-ukraine',
        votes: [
          {
            chamber: 'House' as const,
            congress: 117,
            session: 2,
            rollCall: 65,
            date: '2022-03-10',
            weight: 0.9,
            directionMultiplier: 1,
            kind: 'concur',
          },
        ],
      },
    ];
    const a = buildSeedSql(bills, { isoNow: ISO, traceId: TRACE, newId: () => 'fixed-ulid-row' });
    const b = buildSeedSql(bills, { isoNow: ISO, traceId: TRACE, newId: () => 'fixed-ulid-row' });
    // The bill+vote audit IDs are deterministic from row_id; the row IDs
    // themselves vary unless the test fixes newId. With newId fixed,
    // the entire script is byte-identical.
    expect(a).toBe(b);
  });

  it('handles bills with no votes array', () => {
    counter = 0;
    const bills = [
      { congress: 119, type: 'S', number: '1', title: 't', direction: 'ambiguous' },
    ];
    const sql = buildSeedSql(bills, { isoNow: ISO, traceId: TRACE, newId });
    expect(sql).toContain('INSERT OR IGNORE INTO bills');
    expect(sql).not.toContain('INSERT OR IGNORE INTO votes');
  });

  describe('summary_json truncation (FR-49 AC-49.7)', () => {
    it('preserves a small summary verbatim', () => {
      counter = 0;
      const bills = [{
        congress: 117,
        type: 'HR',
        number: '1',
        title: 't',
        direction: 'pro-ukraine',
        summary: { text: 'short summary text', actionDate: '2024-01-01' },
      }];
      const sql = buildSeedSql(bills, { isoNow: ISO, traceId: TRACE, newId });
      // The summary lands as a JSON literal embedded in a SQL string.
      expect(sql).toMatch(/short summary text/);
      expect(sql).not.toMatch(/truncated/);
    });

    it('truncates a large summary to fit the 8 KB budget with a marker', () => {
      counter = 0;
      const bigText = 'A'.repeat(200_000);
      const bills = [{
        congress: 117,
        type: 'HR',
        number: '1',
        title: 't',
        direction: 'pro-ukraine',
        summary: { text: bigText, actionDate: '2024-01-01' },
      }];
      const sql = buildSeedSql(bills, { isoNow: ISO, traceId: TRACE, newId });
      // The serialized summary_json field SHALL be at most ~8 KB (with a small
      // per-line buffer for SQL escaping).
      const match = sql.match(/'(\{[^']*\\?"text\\?":[^']*\})'/);
      expect(match).not.toBeNull();
      // The truncated literal in the SQL contains the marker.
      expect(sql).toContain('truncated; full summary at congress_gov_url');
      // It does NOT contain the full 200 KB blob.
      expect(sql.length).toBeLessThan(20_000);
    });

    it('omits summary_json when summary is undefined / null', () => {
      counter = 0;
      const bills = [{
        congress: 117,
        type: 'HR',
        number: '1',
        title: 't',
        direction: 'pro-ukraine',
      }];
      const sql = buildSeedSql(bills, { isoNow: ISO, traceId: TRACE, newId });
      // No JSON literal "null" or empty object — when summary is absent,
      // the bill row's summary_json should be SQL NULL.
      expect(sql).not.toMatch(/'null'/);
      // SQL NULL appears in the bills VALUES — check that there is at least
      // one bare NULL token in the bills INSERT.
      const billsInsertMatch = sql.match(/INSERT OR IGNORE INTO bills[^;]+;/s);
      expect(billsInsertMatch).not.toBeNull();
      expect(billsInsertMatch![0]).toMatch(/\bNULL\b/);
    });
  });

  describe('direction_reason placeholder filter (FR-49 AC-49.8)', () => {
    it('drops "manual override" verbatim → NULL', () => {
      counter = 0;
      const bills = [{
        congress: 117,
        type: 'HR',
        number: '1',
        title: 't',
        direction: 'pro-ukraine',
        directionReason: 'manual override',
      }];
      const sql = buildSeedSql(bills, { isoNow: ISO, traceId: TRACE, newId });
      expect(sql).not.toContain("'manual override'");
      // The bill INSERT carries NULL in the direction_reason column slot.
      const billsInsert = sql.match(/INSERT OR IGNORE INTO bills[^;]+;/s)![0];
      expect(billsInsert).toMatch(/\bNULL\b/);
    });

    it('drops "Manual Override" with whitespace (case + trim insensitive)', () => {
      counter = 0;
      const bills = [{
        congress: 117,
        type: 'HR',
        number: '1',
        title: 't',
        direction: 'pro-ukraine',
        directionReason: '  Manual Override  ',
      }];
      const sql = buildSeedSql(bills, { isoNow: ISO, traceId: TRACE, newId });
      expect(sql).not.toMatch(/manual override/i);
    });

    it('preserves substantive direction_reason values verbatim', () => {
      counter = 0;
      const bills = [{
        congress: 117,
        type: 'HR',
        number: '1',
        title: 't',
        direction: 'pro-ukraine',
        directionReason: 'Sanctions on Belarus + Russia',
      }];
      const sql = buildSeedSql(bills, { isoNow: ISO, traceId: TRACE, newId });
      expect(sql).toContain("'Sanctions on Belarus + Russia'");
    });

    it('undefined direction_reason → NULL', () => {
      counter = 0;
      const bills = [{
        congress: 117,
        type: 'HR',
        number: '1',
        title: 't',
        direction: 'pro-ukraine',
      }];
      const sql = buildSeedSql(bills, { isoNow: ISO, traceId: TRACE, newId });
      const billsInsert = sql.match(/INSERT OR IGNORE INTO bills[^;]+;/s)![0];
      expect(billsInsert).toMatch(/\bNULL\b/);
    });
  });

  it('handles a real-shaped curated bill from ukraineBills.json', () => {
    counter = 0;
    const bills = [
      {
        congress: 117,
        type: 'HR',
        number: '2471',
        featured: true,
        label: 'FY22 Consolidated Appropriations',
        title: 'Consolidated Appropriations Act, 2022',
        latestAction: 'Became Public Law No: 117-103.',
        latestActionDate: '2022-03-15',
        becameLaw: true,
        congressGovUrl: 'https://www.congress.gov/bill/117th-congress/house-bill/2471',
        direction: 'pro-ukraine',
        directionReason: 'manual override',
        summary: { text: 'foo', actionDate: '2022-03-15' },
        votes: [
          {
            chamber: 'House' as const,
            congress: 117,
            session: 2,
            rollCall: 65,
            date: '2022-03-10T02:49:07Z',
            url: 'https://clerk.house.gov/evs/2022/roll065.xml',
            action: 'Resolving differences',
            actionDate: '2022-03-09',
            weight: 0.9,
            directionMultiplier: 1,
            kind: 'concur',
          },
        ],
      },
    ];
    const sql = buildSeedSql(bills, { isoNow: ISO, traceId: TRACE, newId });
    // featured bool → 1
    expect(sql).toMatch(/featured.*\n[^]*?\n[^]*?,\s*1,/);
    // becameLaw → 1, congressGovUrl present
    expect(sql).toContain("'https://www.congress.gov/bill/117th-congress/house-bill/2471'");
    // votes inserted with the right kind + weight
    expect(sql).toContain("'concur'");
    expect(sql).toContain('0.9');
    expect(sql).toContain('1'); // direction multiplier
  });
});
